baseURL = "http://example.org/"
languageCode = "en-us"
title = "思考"
theme = "hugo-book"





# hugo discuss 

[params]
BookComments = true
BookDateFormat = '2006/01/02'
disqusShortname = 'your-disqus-shortname'
